### ISSUE TITLE
specifying a register breaks the package

### ISSUE THREAD

**Issue by ninrod** [Dewdrops/evil-ReplaceWithRegister#1]
steps to reproduce:

- yank a word to register `"a`: `"ayiw`

- go to the middle of another word and try to use the gr operator: `"agriw`. 

I get: `if: Symbol’s function definition is void: evil-ReplaceWithRegister/get-register`

**Comment by ninrod** [comment]
Thanks @Dewdrops. I'll test now.

**Comment by Dewdrops** [comment]
Thanks for your feedback. If there are still anything wrong, feel free to reopen this issue.
