### ISSUE TITLE
consider adding to melpa

### ISSUE THREAD

**Issue by ninrod** [Dewdrops/evil-ReplaceWithRegister#2]
Hi, @Dewdrops, your plugin is very useful for vim expatriates comming to emacs. Would you consider adding it to MELPA?

**Comment by Dewdrops** [comment]
https://github.com/melpa/melpa/pull/4422

I've made a PR to MELPA. It seems there are some issues need to be fixed before merging to its master branch. I'll try to address these issues and hopefully we can see this plugin in MELPA soon.

**Comment by Dewdrops** [comment]
Now this package is available in MELPA.

However, the package name and function names are changed (`evil-ReplaceWithRegister` -> `evil-replace-with-register`) to keep emacs lisp convention. You need adjust to the new names to use this plugin via MELPA. Readme is updated.

**Comment by ninrod** [comment]
thank you @Dewdrops. This package is awesome, I use it everyday. Adding it to melpa was a great addition to the archive.
